[2024-11-06T09:27:10.192+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: marketstack_dag.fetch_stock_data scheduled__2024-11-04T00:00:00+00:00 [queued]>
[2024-11-06T09:27:10.208+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: marketstack_dag.fetch_stock_data scheduled__2024-11-04T00:00:00+00:00 [queued]>
[2024-11-06T09:27:10.209+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-11-06T09:27:10.210+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2024-11-06T09:27:10.210+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-11-06T09:27:10.228+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): fetch_stock_data> on 2024-11-04 00:00:00+00:00
[2024-11-06T09:27:10.234+0000] {standard_task_runner.py:52} INFO - Started process 100 to run task
[2024-11-06T09:27:10.240+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'marketstack_dag', 'fetch_stock_data', 'scheduled__2024-11-04T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/stage.py', '--cfg-path', '/tmp/tmpi2b8o32r', '--error-file', '/tmp/tmpxq0dexdw']
[2024-11-06T09:27:10.241+0000] {standard_task_runner.py:80} INFO - Job 35: Subtask fetch_stock_data
[2024-11-06T09:27:10.358+0000] {task_command.py:371} INFO - Running <TaskInstance: marketstack_dag.fetch_stock_data scheduled__2024-11-04T00:00:00+00:00 [running]> on host dd55d6bc6a7f
[2024-11-06T09:27:10.441+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=marketstack_dag
AIRFLOW_CTX_TASK_ID=fetch_stock_data
AIRFLOW_CTX_EXECUTION_DATE=2024-11-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-11-04T00:00:00+00:00
[2024-11-06T09:27:10.764+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stage.py", line 20, in fetch_stock_data
    stock_data = pd.DataFrame(data['data'])
KeyError: 'data'
[2024-11-06T09:27:10.772+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=marketstack_dag, task_id=fetch_stock_data, execution_date=20241104T000000, start_date=20241106T092710, end_date=20241106T092710
[2024-11-06T09:27:10.780+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 35 for task fetch_stock_data ('data'; 100)
[2024-11-06T09:27:10.816+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-11-06T09:27:10.839+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
